
import minimatch from 'minimatch'
test('minimatch', () => {
  const a1 = minimatch('/', '/')
  const a2 = minimatch('/', '/auth/**')
  const a3 = minimatch('/auth', '/')
  const a4 = minimatch('/auth', '/auth**')
  const a5 = minimatch('/reg', '/')
  const a6 = minimatch('/reg', '/auth/**')
  const a7 = minimatch('/auth/reg', '/')
  const a8 = minimatch('/auth/reg', '/auth/**')
  expect(a1).toBe(true)
  expect(a2).toBe(false)
  expect(a3).toBe(false)
  expect(a4).toBe(true)
  expect(a5).toBe(false)
  expect(a6).toBe(false)
  expect(a7).toBe(false)
  expect(a8).toBe(false)
})
